name: Remote-SSH
on:
  repository_dispatch:
  workflow_dispatch:
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup SSH Public Key
      env:
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      run: |
        mkdir -p /home/runner/.ssh
        chmod 700 /home/runner/.ssh
        touch /home/runner/.ssh/authorized_keys
        echo $SSH_PUBLIC_KEY >> /home/runner/.ssh/authorized_keys
        chmod 600 /home/runner/.ssh/authorized_keys
    - name: Setup FRP
      env:
        FRP_SERVER_ADDR: ${{ secrets.FRP_SERVER_ADDR }}
        FRP_SERVER_PORT: ${{ secrets.FRP_SERVER_PORT }}
        FRP_TOKEN: ${{ secrets.FRP_TOKEN }}
        FRP_REMOTE_PORT: ${{ secrets.FRP_REMOTE_PORT }}
        FRP_REMOTE_PORT_W: ${{ secrets.FRP_REMOTE_PORT_W }}
      run: |
        wget -qO /opt/frp.tar.gz https://github.com/fatedier/frp/releases/download/v0.51.3/frp_0.51.3_linux_amd64.tar.gz
        tar -zxvf /opt/frp.tar.gz -C /opt
        mv /opt/frp_0.51.3_linux_amd64 /opt/frp
        sed -i "s/server_addr = .*/server_addr = $FRP_SERVER_ADDR/" /opt/frp/frpc.ini
        sed -i "s/server_port = .*/server_port = $FRP_SERVER_PORT/" /opt/frp/frpc.ini
        sed -i "/^\[ssh\]/i token = $FRP_TOKEN" /opt/frp/frpc.ini
        sed -i "s/remote_port = .*/remote_port = $FRP_REMOTE_PORT/" /opt/frp/frpc.ini
        echo "[xray_github_action_666]\ntype = tcp\nlocal_ip = 127.0.0.1\nlocal_port = 9797\nremote_port = $FRP_REMOTE_PORT_W" >> /opt/frp/frpc.ini
        nohup /opt/frp/frpc -c /opt/frp/frpc.ini > /dev/null 2>&1 &
    - name: Setup Xray
      run: |
        sudo bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install --beta
        sudo mkdir -p /usr/local/etc/xray
        sudo touch /usr/local/etc/xray/config.json
        sudo chmod 777 /usr/local/etc/xray/config.json
    - name: Setup Xray configs
      uses: cuchi/jinja2-action@v1.2.0
      with:
        template: /home/runner/work/OP-bot/OP-bot/config_opxray_server.json.j2
        output_file: config_opxray_server.json
      env:
        XRAY_UUID: ${{ secrets.XRAY_UUID }}
        XRAY_PRIVATE_KEY: ${{ secrets.XRAY_PRIVATE_KEY }}
        XRAY_SHORT_ID: ${{ secrets.XRAY_SHORT_ID }}
    - name: Restart Xray
      run: |
        systemctl restart xray
    - name: Free Space
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android /opt/ghc
        sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Wait
      uses: GuillaumeFalourd/wait-sleep-action@v1
      with:
        time: '6h'
